services:
  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway_local
    ports:
      - "9091:9091"
    networks:
      - airflow

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_local
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - airflow

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_local
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
    networks:
      - airflow
