global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "pushgateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["pushgateway:9091"]
    # Drop any job that looks like a test to avoid test pushes polluting dashboard
    metric_relabel_configs:
      - source_labels: ["job"]
        regex: "test_.*"
        action: drop
